"""alspec: Building blocks for many-sorted algebraic specifications."""

from .axiom_match import (
    AxiomCellMatch,
    CellCoverage,
    CoverageStatus,
    MatchKind,
    MatchReport,
    match_spec,
    match_spec_sync,
)

from .helpers import (
    S,
    app,
    atomic,
    conjunction,
    const,
    definedness,
    disjunction,
    eq,
    exists,
    field_access,
    fn,
    forall,
    iff,
    implication,
    negation,
    param,
    pred,
    pred_app,
    var,
)
from .result import Err, Ok, Result
from .serialization import dumps, loads
from .signature import (
    FnParam,
    FnSymbol,
    GeneratedSortInfo,
    PredSymbol,
    Signature,
    Totality,
)
from .sorts import (
    AtomicSort,
    CoproductAlt,
    CoproductSort,
    ProductField,
    ProductSort,
    SortDecl,
    SortKind,
    SortRef,
)
from .spec import Axiom, Spec
from .terms import (
    Biconditional,
    Conjunction,
    Definedness,
    Disjunction,
    Equation,
    ExistentialQuant,
    FieldAccess,
    FnApp,
    Formula,
    Implication,
    Literal,
    Negation,
    PredApp,
    Term,
    UniversalQuant,
    Var,
)

__all__ = [
    # --- Construction Helpers (use THESE to build specs) ---
    "S",
    "atomic",
    "param",
    "fn",
    "pred",
    "var",
    "app",
    "const",
    "eq",
    "forall",
    "exists",
    "iff",
    "negation",
    "conjunction",
    "disjunction",
    "implication",
    "pred_app",
    "definedness",
    "field_access",
    # --- Assembly (spec-level, not formula-level) ---
    "Axiom",
    "Spec",
    "Signature",
    "GeneratedSortInfo",
    "Totality",
    # --- Sort declarations ---
    "AtomicSort",
    "CoproductAlt",
    "CoproductSort",
    "ProductField",
    "ProductSort",
    "SortDecl",
    "SortKind",
    "SortRef",
    # --- Signature components ---
    "FnParam",
    "FnSymbol",
    "PredSymbol",
    # --- Types (for isinstance checks in internal/analysis code, NOT for construction) ---
    "Biconditional",
    "Conjunction",
    "Definedness",
    "Disjunction",
    "Equation",
    "ExistentialQuant",
    "FieldAccess",
    "FnApp",
    "Formula",
    "Implication",
    "Literal",
    "Negation",
    "PredApp",
    "Term",
    "UniversalQuant",
    "Var",
    # --- Axiom matching ---
    "AxiomCellMatch",
    "CellCoverage",
    "CoverageStatus",
    "MatchKind",
    "MatchReport",
    "match_spec",
    "match_spec_sync",
    # --- Serialization ---
    "dumps",
    "loads",
    # --- Result ---
    "Ok",
    "Err",
    "Result",
]
